name: Build and deploy app

on:
    push:
        branches:
            - master
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Create SSH key
                run: |
                  echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa 
                  chmod 600 ~/.ssh/id_rsa
            - name: Building docker image
              env:
                DOCKER_HOST: ssh://${{secrets.REMOTE}}
              run: docker build -t movies-series:latest .
            - name: Clear dangling images
              env:
                DOCKER_HOST: ssh://${{secrets.REMOTE}}
              run: docker image prune

    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - uses: actions/checkout@v3
            - uses: webfactory/ssh-agent@v0.7.0
              with:
                  ssh-private-key: ${{secrets.KEY}}

            - name: Stopping old application
              env:
                DOCKER_HOST: ssh://${{secrets.REMOTE}}
              run: docker stop movies-series && docker rm movies-series
            - name: Deploying new application
              env:
                DOCKER_HOST: ssh://${{secrets.REMOTE}}
              run: docker run -d --name movies-series -p 127.0.0.1:2082:3000 movies-series:latest
