name: Build and deploy app

on:
    push:
        branches:
            - master
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: webfactory/ssh-agent@v0.7.0
              with:
                  ssh-private-key: ${{secrets.KEY}}

            - name: Building docker image
              run: docker -H ssh://${{secrets.REMOTE}} build -t movies-series:latest .
            - name: Clear dangling images
              run: docker -H ssh://${{secrets.REMOTE}} image prune

    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - uses: actions/checkout@v3
            - uses: webfactory/ssh-agent@v0.7.0
              with:
                  ssh-private-key: ${{secrets.KEY}}

            - name: Stopping old application
              run: docker -H ssh://${{secrets.REMOTE}} stop movies-series && docker -H ssh://${{secrets.REMOTE}} rm movies-series
            - name: Deploying new application
              run: docker -H ssh://${{secrets.REMOTE}} run -d --name movies-series -p 127.0.0.1:2082:3000 movies-series:latest
