name: Build app

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: docker.nexus.themcbrothers.net
          username: ${{secrets.USER}}
          password: ${{secrets.PWD}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: docker.nexus.themcbrothers.net/movies-series:latest
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@3

      - name: Deploy docker container
        uses: joelwmale/webhook-action@master
        env:
          WEBHOOK_URL: ${{secrets.DEPLOY_HOOK}}